FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --force --only=production

FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG CASHFREE_BASE_URL
ARG CASHFREE_SECRET_KEY
ARG CASHFREE_APP_ID
ARG SUPABASE_SERVICE_KEY
ARG NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
    DATABASE_URL=$DATABASE_URL \
    DIRECT_URL=$DIRECT_URL \
    CASHFREE_BASE_URL=$CASHFREE_BASE_URL \
    CASHFREE_SECRET_KEY=$CASHFREE_SECRET_KEY \
    CASHFREE_APP_ID=$CASHFREE_APP_ID \
    SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
RUN npx next build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production \
    HOSTNAME=0.0.0.0 \
    PORT=3000
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]